version: '3.9'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]